### PR TITLE
TeslaMate encryption of API tokens

### PR DESCRIPTION
**Pull request by tobiasehlert**
Adds support for AES_256_GCM encrypted API tokens implemented by PR https://github.com/adriankumpf/teslamate/pull/2360 in TeslaMate.

### CODE REVIEW

**Comment by noocyte** [comment]
@tobiasehlert What is left before this can be merged?

**Comment by tobiasehlert** [comment]
> @tobiasehlert What is left before this can be merged?

@noocyte, the problem is that the decryption doesn't work and I was kind of stuck.
@LelandSindt seems to have solved the decryption.. trying his code in 51306bf to see if it works :)

**Comment by pkuehnel** [comment]
Could you please mention in your new [Release notes](https://github.com/tobiasehlert/teslamateapi/releases/tag/v1.15.0), that you have to add the encryption key to your service section as well?

**Comment by tobiasehlert** [comment]
@pkuehnel I did mention that in the beginning and updated the readme with the ENCRYPTION_KEY parameter.
But I can make it more clear :)

**Pull request merged**
