### PR TITLE
proxy commands to Tesla API

### PR DESCRIPTION
**Pull request by LelandSindt**
Addresses https://github.com/tobiasehlert/teslamateapi/issues/6

### CODE REVIEW

**Comment by tobiasehlert** [comment]
Hi @LelandSindt 

Have you unchecked the "Allow edits from maintainers."? I can't push changes to the PR hehe

**Comment by LelandSindt** [comment]
:man_shrugging: 

image

**Comment by LelandSindt** [comment]
I will look again tonight... or... you can complete the PR, and make your changes on your `feature-commands` branch.

**Comment by tobiasehlert** [comment]
Maybe something that can only be done by creating the PR.. but doesn't matter not. I'll merge this PR and change in the branch :)

image

**Pull request merged**
