### PR TITLE
feat: add odometer information to charge-endpoints

### PR DESCRIPTION
**Pull request by herrfrei**
As described in #312

### CODE REVIEW

**Review by tobiasehlert — COMMENTED** [review]
Looks good so far! 🚀 

The thing that I'd like to see as well is the addition to the _TeslaMateAPICarsChargesDetails_ as well.
Will you add that as well?

**Comment by herrfrei** [comment]
Ok, I did it!

**Review by tobiasehlert — APPROVED** [review]
ready to merge 🚀

**Comment by tobiasehlert** [comment]
@herrfrei, this feature release in [v1.20.0](https://github.com/tobiasehlert/teslamateapi/releases/tag/v1.20.0).
Thanks for your contribution :)

**Pull request merged**
