### PR TITLE
Fix for issue #176

### PR DESCRIPTION
**Pull request by virusbrain**
This will fix https://github.com/tobiasehlert/teslamateapi/issues/176

We have found out that teslamateapi will not resubscribe to the MQTT topics after a reconnect of the connection to the MQTT service occured. Now the subscription will be renewed on reconnection. 

And with this pull request users are able to manipulate the mqtt client id which is the identifier for the client at the mqtt service.

### CODE REVIEW

**Review by tobiasehlert — APPROVED** [review]
Looks good to me 👍

**Comment by tobiasehlert** [comment]
Thanks for the PR @virusbrain and @LelandSindt ⭐

**Comment by vbarrier** [comment]
Thank you 🙏

Do we know when it will be released?

**Comment by virusbrain** [comment]
> Thank you 🙏
> 
> Do we know when it will be released?

Seems it is already released: https://github.com/tobiasehlert/teslamateapi/releases/tag/v1.16.0

**Pull request merged**
